#ifndef __CHOREO_GCU_ACORE_MMA_H__
#define __CHOREO_GCU_ACORE_MMA_H__

// Choreo runtime wrappers for acore::matmul with VACC accumulation semantics.
//
// These templates hide the acc_flag/store_flag/launch_times choreography
// from generated code. Each maps directly to a single acore::matmul call
// with the appropriate flag combination.
//
// Usage (generated by TopsccCodeGen::Visit(AST::MMA&)):
//   choreo::mma_exec_init  -- first K tile: initialize VACC
//   choreo::mma_exec_accum -- middle K tiles: accumulate into VACC
//   choreo::mma_exec_store -- last K tile: accumulate and write back
//   choreo::mma_exec_single -- single tile: init + store in one call

#ifdef __ACORE_OP__
  #include <common/acore_op.h>
#endif

namespace choreo {

// First K tile: init VACC, keep in VACC (no store)
template <int M, int Format>
__device__ void mma_exec_init(void* out, void* lhs, void* rhs, int* ws, int K,
                              int N, int vab_off = 0) {
#ifdef __ACORE_OP__
  acore::matmul<M, Format>(out, lhs, rhs, (void*)nullptr, ws, K, N,
                           /*acc=*/0, /*store=*/0, /*bias=*/0, vab_off,
                           /*launch_times=*/0);
#endif
}

// Middle K tiles: accumulate into existing VACC, no store
template <int M, int Format>
__device__ void mma_exec_accum(void* out, void* lhs, void* rhs, int* ws, int K,
                               int N, int vab_off = 0) {
#ifdef __ACORE_OP__
  acore::matmul<M, Format>(out, lhs, rhs, (void*)nullptr, ws, K, N,
                           /*acc=*/1, /*store=*/0, /*bias=*/0, vab_off,
                           /*launch_times=*/1);
#endif
}

// Last K tile: accumulate and write VACC to output
template <int M, int Format>
__device__ void mma_exec_store(void* out, void* lhs, void* rhs, int* ws, int K,
                               int N, int vab_off = 0) {
#ifdef __ACORE_OP__
  acore::matmul<M, Format>(out, lhs, rhs, (void*)nullptr, ws, K, N,
                           /*acc=*/1, /*store=*/1, /*bias=*/0, vab_off,
                           /*launch_times=*/1);
#endif
}

// Single tile: init VACC and immediately store (no K-loop)
template <int M, int Format>
__device__ void mma_exec_single(void* out, void* lhs, void* rhs, int* ws, int K,
                                int N, int vab_off = 0) {
#ifdef __ACORE_OP__
  acore::matmul<M, Format>(out, lhs, rhs, (void*)nullptr, ws, K, N,
                           /*acc=*/0, /*store=*/1, /*bias=*/0, vab_off,
                           /*launch_times=*/0);
#endif
}

} // namespace choreo

#endif // __CHOREO_GCU_ACORE_MMA_H__
