stages:
  - check-in-tests
  - doc-gen


gputest:
  stage: check-in-tests
  script:
    - echo "Running tests with GPU..."
    - make ci-gpu-test
  tags:
    - GPU
  only:
    - main
    - release/alpha
    - merge_requests

gcu2test:
  stage: check-in-tests
  script:
    - echo "Running tests with GCU2..."
    - make ci-gcu2-test
  tags:
    - GCU2
  only:
    - main
    - release/alpha
    - merge_requests

gcu3test:
  stage: check-in-tests
  script:
    - echo "Running tests with GCU3 S60..."
    - make ci-gcu3-test
  tags:
    - GCU3
  only:
    - main 
    - release/alpha
    - merge_requests

generate_docs:
  stage: doc-gen
  tags:
    - DOC
  script:
    - echo "Setting up environment for documentation generation ..."
    - python3.8 -m pip install mkdocs mkdocs-material mkdocs-markdownextradata-plugin 
    - make serve-doc

cache:
  paths:
    - venv/ 
    - .cache/pip/
