site_name: Choreo Tutorials
site_url: http://127.0.0.1:8000

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - search.highlight
    - content.code.annotate

docs_dir: Documents/Documentation

extra_javascript:
  - assets/js/highlight.min.js
  - assets/js/choreo.js
  - assets/js/bash.min.js

extra_css:
  - assets/css/github-dark.min.css
  - assets/css/choreo.css

markdown_extensions:
  - codehilite:
      guess_lang: false
      css_class: highlight
  - toc:
      permalink: true

nav:
  - Home: index.md
  - What is Choreo: what-is-choreo.md
  - Basics of Choreo-C++ Program:
    - Choreo-C++ Program Structure: choreo-program-structure.md
    - Manipulating the Shaped Data:
      - Shape and MDSpan: shape-in-choreo.md
      - Integers and I-Tuples: integer-ituple.md
      - Spanned Data and Buffers: spanned-data.md
      - Dynamic Shape: symbolic-shape.md
    - Looping and Parallel Execution:
      - Prelude: intro-loop-parallel.md
      - SPMD Parallellism: parallel-in-choreo.md
      - Loop Control: within-loops.md
    - Move Data in Chunks:
      - Data Movement Basics: basic-dma.md
      - Data Tiling and ChunkAt: tiling-chunkat.md
    - C++ Embedding of Choreo Function:
      - From Host to Tileflow: host-to-tileflow.md
      - Call Device Program in Tileflow: call-in-choreo.md
    - Advanced Features:
      - Advanced In Program Control: loop-in-advance.md
      - Advanced In DMA: dma-in-advance.md
    - Miscellaneous:
      - Macro and Preprocessing: macro-in-choreo.md
      - Check Tileflow Program Statically: compiler-func.md
      - Useful Utilities: assertion.md
  - A Whirlwind Tour to Optimisation Patterns:
    - Tileflow Optimisations: tileflow-opt.md
    - Asynchoronous DMA transfer patterns with Choreo: async-dma-patterns.md
    - Multi-buffering Patterns with Choreo: multi-buffering-patterns.md
  - Reference Palette on Operators: operator-samples.md
  - Design Rationales:
    - Syntax Design of Choreo: syntax-design-of-choreo.md
    - Why Symbolic Shapes: why-symbolic-shapes.md
    - Design of Symbolic Evaluation System: value-numbering.md
    - Dynaminism Support with Symbolic Representation: dynamic-design.md
  - Contributing to Choreo: contribute.md
