site_name: Choreo Tutorials
site_url: http://127.0.0.1:8000

theme:
  name: material 

markdown_extensions:
  - toc:
      permalink: true


docs_dir: Documents/Tutorials 

nav:
  - Home: index.md
  - Getting Started with Choreo: getting-started-with-choreo.md
  - What is Choreo: what-is-choreo.md
  - Basics of Choreo Program:
    - Choreo Program Structure: choreo-program-structure.md
    - Abstractions and Syntax in Choreo Function:
      - Shape/Data in Choreo: shape-in-choreo.md
      - Memory in Choreo: memory-in-choreo.md
      - DMA in Choreo: dma-in-choreo.md
      - Call Statements in Choreo: call-in-choreo.md
      - Parallelism in Choreo: parallel-in-choreo.md
      - Macro Utility in Choreo: macro-in-choreo.md
  - A Whirlwind Tour to Optimisation Patterns: 
    - Tileflow Optimisations: tileflow-opt.md
    - Asynchoronous DMA transfer patterns with Choreo: async-dma-patterns.md
    - Multi-buffering Patterns with Choreo: mutli-buffering-patterns.md
  - Reference Palette on Operators: operator-samples.md
  - Design Rationales:
    - Syntax Design of Choreo: syntax-design-of-choreo.md
    - Design of Symbolic Evaluation System: symbolic-evaluation.md
    - Dynaminism Support with Symbolic Representation: dynamic-design.md
  - Contributing to Choreo: contribute.md

